#!/bin/sh
SERVICE_HOME=~/coolscreen-services/coolscreen-offline-datadeal-service
SERVICE_EXE=$SERVICE_HOME/libs/coolscreen-offline-datadeal-service-1.0.jar
SERVICE_PROP=$SERVICE_HOME/resources/offline_dd_service.xml
#MAIN_CLASS=cn.wanda.idc.coolscreen.datadeal.CustomerLevelAndUsingAppTime
MAIN_CLASS=cn.wanda.idc.coolscreen.offline.dd.main.Main

for file in $SERVICE_HOME/libs/*.jar
do
        wifiJars=$wifiJars`echo -n $file":"`
done
jar_files=${wifiJars%?}

export CLASSPATH=$jar_files:.:$CLASSPATH

#spark-submit --master yarn --deploy-mode client --driver-memory 8G --executor-memory 5G --num-executors 6 --class $MAIN_CLASS  $SERVICE_EXE
java  -cp $CLASSPATH  $MAIN_CLASS  $SERVICE_PROP